/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-11-08 05:12:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import webContent.contentDAO;
import webContent.BurgerInfo;
import webContent.UserInfo;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String no = request.getParameter("no");
int b_no;
if(no != null && no != "" && no != "null")
{
	try
	{
		b_no = Integer.parseInt(no);
		
      out.write("\r\n");
      out.write("\t\t");
contentDAO a = new contentDAO(b_no); 
      out.write("\r\n");
      out.write("\t\t");
a.conn(); 
      out.write("\r\n");
      out.write("\t\t");
BurgerInfo b = a.getBurgerInfo(); 
      out.write("\r\n");
      out.write("\t\t");
UserInfo u = a.getUserInfo(); 
      out.write("\r\n");
      out.write("\t\t");
b.getName(); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"infobox vcard\">\r\n");
      out.write("\t\t<caption><span class=\"fn\"><font size=\"5\"><b>");
      out.print(b.getName() );
      out.write("</b></font></span></caption>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t<img alt=\"");
      out.print(b.getName() );
      out.write("\" src=\"");
      out.print(b.getImage() );
      out.write("\" width=\"180\" height=\"207\"  />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th style=\"font-weight:bold;\">브랜드</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getCompany() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th style=\"font-weight:bold;\">칼로리(Kcal)</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getCalone() );
      out.write("(단품)<br>");
      out.print(b.getCalset() );
      out.write("(세트)</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th style=\"font-weight:bold;\">가격(KRW)</th>\r\n");
      out.write("\t\t<td>");
      out.print(b.getPriceone() );
      out.write("(단품)<br>");
      out.print(b.getPriceset() );
      out.write("(세트)</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t");
      out.print(b.getContent() );
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");
      out.print(b.getModified());
      out.write('에');
      out.write(' ');
      out.print(u.getId() );
      out.write("님이 수정(E-mail : ");
      out.print(u.getEmail() );
      out.write(')');
      out.write('\r');
      out.write('\n');
	}
	catch(Exception e)
	{
		
      out.write("Something Error.\r\n");
      out.write("\t\t");
      out.print(no );
      out.write("\r\n");
      out.write("\t\t");

	}
		
}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
